name: Minecraft Neoforge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: container-registry.oracle.com/graalvm/jdk:latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Yarik217/neoforge:$(date +%s)
